Region.create(name: "Kanto")
Region.create(name: "Johto")
Region.create(name: "Hoenn")
Region.create(name: "Sinnoh")
Region.create(name: "Unova")
Region.create(name: "Kalos")
Region.create(name: "Aloha")

Type.create(type_name: "Water")
Type.create(type_name: "Fire")
Type.create(type_name: "Grass")
Type.create(type_name: "Flying")
Type.create(type_name: "Rock")
Type.create(type_name: "Ground")
Type.create(type_name: "Fighting")
Type.create(type_name: "Dragon")
Type.create(type_name: "Steel")
Type.create(type_name: "Normal")
Type.create(type_name: "Psychic")
Type.create(type_name: "Ghost")
Type.create(type_name: "Dark")
Type.create(type_name: "Electric")
Type.create(type_name: "Bug")
Type.create(type_name: "Ice")
Type.create(type_name: "Fairy")
Type.create(type_name: "Poison")



Trainer.create(name: "Lorelei", region_id: 1, title: "First", type_id: 16)
Trainer.create(name: "Bruno", region_id: 1, title: "Second", type_id: 7)
Trainer.create(name: "Agatha", region_id: 1, title: "Third", type_id: 12)
Trainer.create(name: "Lance", region_id: 1, title: "Fourth", type_id: 8)
Trainer.create(name: "Blue", region_id: 1, title: "Champion", type_id: nil)

Trainer.create(name: "Will", region_id: 2, title: "First", type_id: 11)
Trainer.create(name: "Koga", region_id: 2, title: "Second", type_id: 18)
Trainer.create(name: "Bruno", region_id: 2, title: "Third", type_id: 7)
Trainer.create(name: "Karen", region_id: 2, title: "Fourth", type_id: 13)
Trainer.create(name: "Lance", region_id: 2, title: "Champion", type_id: 8)

Trainer.create(name: "Sidney", region_id: 3, title: "First", type_id: 13)
Trainer.create(name: "Phoebe", region_id: 3, title: "Second", type_id: 12)
Trainer.create(name: "Glacia", region_id: 3, title: "Third", type_id: 16)
Trainer.create(name: "Drake", region_id: 3, title: "Fourth", type_id: 8)
Trainer.create(name: "Steven", region_id: 3, title: "Champion", type_id: 9)

Trainer.create(name: "Aaron", region_id: 4, title: "First", type_id: 15)
Trainer.create(name: "Bertha", region_id: 4, title: "Second", type_id: 6)
Trainer.create(name: "Flint", region_id: 4, title: "Third", type_id: 2)
Trainer.create(name: "Lucian", region_id: 4, title: "Fourth", type_id: 11)
Trainer.create(name: "Cynthia", region_id: 4, title: "Champion", type_id: nil)

Trainer.create(name: "Shauntal", region_id: 5, title: "First", type_id: 12)
Trainer.create(name: "Marshal", region_id: 5, title: "Second", type_id: 7)
Trainer.create(name: "Grimsley", region_id: 5, title: "Third", type_id: 13)
Trainer.create(name: "Caitlin", region_id: 5, title: "Fourth", type_id: 11)
Trainer.create(name: "Alder", region_id: 5, title: "Champion", type_id: nil)

Trainer.create(name: "Malva", region_id: 6, title: "First", type_id: 2)
Trainer.create(name: "Siebold", region_id: 6, title: "Second", type_id: 1)
Trainer.create(name: "Wikstrom", region_id: 6, title: "Third", type_id: 9)
Trainer.create(name: "Drasna", region_id: 6, title: "Fourth", type_id: 8)
Trainer.create(name: "Diantha", region_id: 6, title: "Champion", type_id: nil)

Trainer.create(name: "Hala", region_id: 7, title: "First", type_id: 7)
Trainer.create(name: "Olivia", region_id: 7, title: "Second", type_id: 5)
Trainer.create(name: "Acerola", region_id: 7, title: "Third", type_id: 12)
Trainer.create(name: "Kahili", region_id: 7, title: "Fourth", type_id: 4)
Trainer.create(name: "Kukui", region_id: 7, title: "Champion", type_id: nil)

Pokemon.create(name: "Dewgong", trainer_id: 1, type1_id:1, type2_id: 16, level: 51)
Pokemon.create(name: "Jynx", trainer_id: 1, type1_id:11, type2_id: 16, level: 51)
Pokemon.create(name: "Cloyster", trainer_id: 1, type1_id:1, type2_id: 16, level: 51)
Pokemon.create(name: "Slowbro", trainer_id: 1, type1_id:1, type2_id: 11, level: 51)
Pokemon.create(name: "Lapras", trainer_id: 1, type1_id:1, type2_id: 16, level: 52)

Pokemon.create(name: "Onyx", trainer_id: 2, type1_id:5, type2_id: 6, level: 52)
Pokemon.create(name: "Hitmochan", trainer_id: 2, type1_id:11, type2_id: 16, level: 52)
Pokemon.create(name: "Hitmonlee", trainer_id: 2, type1_id:7, type2_id: nil, level: 52)
Pokemon.create(name: "Poliwrath", trainer_id: 2, type1_id:1, type2_id: 7, level: 52)
Pokemon.create(name: "Machamp", trainer_id: 2, type1_id:7, type2_id: nil, level: 53)
puts "✅ Done seeding!"
