Region.create(name: "Kanto")
Region.create(name: "Johto")
Region.create(name: "Hoenn")
Region.create(name: "Sinnoh")
Region.create(name: "Unova")
Region.create(name: "Kalos")
Region.create(name: "Aloha")

Type.create(type_name: "Water")
Type.create(type_name: "Fire")
Type.create(type_name: "Grass")
Type.create(type_name: "Flying")
Type.create(type_name: "Rock")
Type.create(type_name: "Ground")
Type.create(type_name: "Fighting")
Type.create(type_name: "Dragon")
Type.create(type_name: "Steel")
Type.create(type_name: "Normal")
Type.create(type_name: "Psychic")
Type.create(type_name: "Ghost")
Type.create(type_name: "Dark")
Type.create(type_name: "Electric")
Type.create(type_name: "Bug")
Type.create(type_name: "Ice")
Type.create(type_name: "Fairy")
Type.create(type_name: "Poison")



Trainer.create(name: "Lorelei", region_id: 1, title: "First", type_id: 16)
Trainer.create(name: "Bruno", region_id: 1, title: "Second", type_id: 7)
Trainer.create(name: "Agatha", region_id: 1, title: "Third", type_id: 12)
Trainer.create(name: "Lance", region_id: 1, title: "Fourth", type_id: 8)
Trainer.create(name: "Blue", region_id: 1, title: "Champion", type_id: nil)

Trainer.create(name: "Will", region_id: 2, title: "First", type_id: 11)
Trainer.create(name: "Koga", region_id: 2, title: "Second", type_id: 18)
Trainer.create(name: "Bruno", region_id: 2, title: "Third", type_id: 7)
Trainer.create(name: "Karen", region_id: 2, title: "Fourth", type_id: 13)
Trainer.create(name: "Lance", region_id: 2, title: "Champion", type_id: 8)

Trainer.create(name: "Sidney", region_id: 3, title: "First", type_id: 13)
Trainer.create(name: "Phoebe", region_id: 3, title: "Second", type_id: 12)
Trainer.create(name: "Glacia", region_id: 3, title: "Third", type_id: 16)
Trainer.create(name: "Drake", region_id: 3, title: "Fourth", type_id: 8)
Trainer.create(name: "Steven", region_id: 3, title: "Champion", type_id: 9)

Trainer.create(name: "Aaron", region_id: 4, title: "First", type_id: 15)
Trainer.create(name: "Bertha", region_id: 4, title: "Second", type_id: 6)
Trainer.create(name: "Flint", region_id: 4, title: "Third", type_id: 2)
Trainer.create(name: "Lucian", region_id: 4, title: "Fourth", type_id: 11)
Trainer.create(name: "Cynthia", region_id: 4, title: "Champion", type_id: nil)

Trainer.create(name: "Shauntal", region_id: 5, title: "First", type_id: 12)
Trainer.create(name: "Marshal", region_id: 5, title: "Second", type_id: 7)
Trainer.create(name: "Grimsley", region_id: 5, title: "Third", type_id: 13)
Trainer.create(name: "Caitlin", region_id: 5, title: "Fourth", type_id: 11)
Trainer.create(name: "Alder", region_id: 5, title: "Champion", type_id: nil)

Trainer.create(name: "Malva", region_id: 6, title: "First", type_id: 2)
Trainer.create(name: "Siebold", region_id: 6, title: "Second", type_id: 1)
Trainer.create(name: "Wikstrom", region_id: 6, title: "Third", type_id: 9)
Trainer.create(name: "Drasna", region_id: 6, title: "Fourth", type_id: 8)
Trainer.create(name: "Diantha", region_id: 6, title: "Champion", type_id: nil)

Trainer.create(name: "Hala", region_id: 7, title: "First", type_id: 7)
Trainer.create(name: "Olivia", region_id: 7, title: "Second", type_id: 5)
Trainer.create(name: "Acerola", region_id: 7, title: "Third", type_id: 12)
Trainer.create(name: "Kahili", region_id: 7, title: "Fourth", type_id: 4)
Trainer.create(name: "Kukui", region_id: 7, title: "Champion", type_id: nil)

Pokemon.create(name: "Dewgong", trainer_id: 1, type1_id:1, type2_id: 16, level: 51)
Pokemon.create(name: "Jynx", trainer_id: 1, type1_id:11, type2_id: 16, level: 51)
Pokemon.create(name: "Cloyster", trainer_id: 1, type1_id:1, type2_id: 16, level: 51)
Pokemon.create(name: "Slowbro", trainer_id: 1, type1_id:1, type2_id: 11, level: 51)
Pokemon.create(name: "Lapras", trainer_id: 1, type1_id:1, type2_id: 16, level: 52)

Pokemon.create(name: "Onyx", trainer_id: 2, type1_id:5, type2_id: 6, level: 52)
Pokemon.create(name: "Hitmochan", trainer_id: 2, type1_id:11, type2_id: 16, level: 52)
Pokemon.create(name: "Hitmonlee", trainer_id: 2, type1_id:7, type2_id: nil, level: 52)
Pokemon.create(name: "Poliwrath", trainer_id: 2, type1_id:1, type2_id: 7, level: 52)
Pokemon.create(name: "Machamp", trainer_id: 2, type1_id:7, type2_id: nil, level: 53)

Pokemon.create(name: "Arbok", trainer_id: 3, type1_id:18, type2_id: nil, level: 53)
Pokemon.create(name: "Gengar", trainer_id: 3, type1_id:12, type2_id: 18, level: 53)
Pokemon.create(name: "Golbat", trainer_id: 3, type1_id:18, type2_id: 4, level: 53)
Pokemon.create(name: "Weezing", trainer_id: 3, type1_id:18, type2_id: nil, level: 53)
Pokemon.create(name: "Gengar", trainer_id: 3, type1_id:12, type2_id: 18, level: 54)

Pokemon.create(name: "Seadra", trainer_id: 4, type1_id: 1, type2_id: nil, level: 54)
Pokemon.create(name: "Aerodactyl", trainer_id: 4, type1_id: 4, type2_id: 5, level: 54)
Pokemon.create(name: "Gyarados", trainer_id: 4, type1_id: 1, type2_id: 4, level: 54)
Pokemon.create(name: "Charizard", trainer_id: 4, type1_id: 2, type2_id: 4, level: 54)
Pokemon.create(name: "Dragonite", trainer_id: 4, type1_id: 8, type2_id: 4, level: 55)

Pokemon.create(name: "Heracross", trainer_id: 5, type1_id:7, type2_id: 15, level: 72)
Pokemon.create(name: "Alakazam", trainer_id: 5, type1_id:11, type2_id: nil, level: 73)
Pokemon.create(name: "Tyranitar", trainer_id: 5, type1_id:5, type2_id: 13, level: 72)
Pokemon.create(name: "Gyarados", trainer_id: 5, type1_id:1, type2_id: 4, level: 73)
Pokemon.create(name: "Arcanine", trainer_id: 5, type1_id:2, type2_id: nil, level: 73)
Pokemon.create(name: "Venusaur", trainer_id: 5, type1_id:3, type2_id: 18, level: 75)

Pokemon.create(name: "Xatu", trainer_id: 6, type1_id: 4, type2_id: 11, level: 40)
Pokemon.create(name: "Jynx", trainer_id: 6, type1_id: 16, type2_id: 11, level: 41)
Pokemon.create(name: "Slowbro", trainer_id: 6, type1_id: 1, type2_id: 11, level: 41)
Pokemon.create(name: "Exeggutor", trainer_id: 6, type1_id: 3, type2_id: 11, level: 41)
Pokemon.create(name: "Xatu", trainer_id: 6, type1_id: 4, type2_id: 11, level: 42)

Pokemon.create(name: "Ariados", trainer_id: 7, type1_id: 15, type2_id: 18, level: 40)
Pokemon.create(name: "Forretress", trainer_id: 7, type1_id: 15, type2_id: 9, level: 43)
Pokemon.create(name: "Muk", trainer_id: 7, type1_id: 18, type2_id: nil, level: 42)
Pokemon.create(name: "Venomoth", trainer_id: 7, type1_id: 15, type2_id: 18, level: 41)
Pokemon.create(name: "Crobat", trainer_id: 7, type1_id: 4, type2_id: 18, level: 44)

Pokemon.create(name: "Hitmontop", trainer_id: 8, type1_id: 7, type2_id: nil, level: 42)
Pokemon.create(name: "Hitmonlee", trainer_id: 8, type1_id: 7, type2_id: nil, level: 42)
Pokemon.create(name: "Hitmonchan", trainer_id: 8, type1_id: 7, type2_id: nil, level: 42)
Pokemon.create(name: "Onyx", trainer_id: 8, type1_id: 5, type2_id: 6, level: 43)
Pokemon.create(name: "Machamp", trainer_id: 8, type1_id: 7, type2_id: nil, level: 46)

Pokemon.create(name: "Umbreon", trainer_id: 9, type1_id: 13, type2_id: nil, level: 42)
Pokemon.create(name: "Vileplume", trainer_id: 9, type1_id: 3, type2_id: 18, level: 42)
Pokemon.create(name: "Murkrow", trainer_id: 9, type1_id: 4, type2_id: 13, level: 44)
Pokemon.create(name: "Gengar", trainer_id: 9, type1_id: 18, type2_id: 12, level: 45)
Pokemon.create(name: "Houndoom", trainer_id: 9, type1_id: 2, type2_id: 13, level: 47)

Pokemon.create(name: "Gyarados", trainer_id: 10, type1_id: 4, type2_id: 1, level: 44)
Pokemon.create(name: "Dragonite", trainer_id: 10, type1_id: 4, type2_id: 8, level: 49)
Pokemon.create(name: "Dragonite", trainer_id: 10, type1_id: 4, type2_id: 8, level: 49)
Pokemon.create(name: "Aerodactyl", trainer_id: 10, type1_id: 4, type2_id: 5, level: 48)
Pokemon.create(name: "Charizard", trainer_id: 10, type1_id: 4, type2_id: 2, level: 48)
Pokemon.create(name: "Dragonite", trainer_id: 10, type1_id: 4, type2_id: 8, level: 50)

Pokemon.create(name: "Mightyena", trainer_id: 11, type1_id: 13, type2_id: nil, level: 50)
Pokemon.create(name: "Shiftry", trainer_id: 11, type1_id: 3, type2_id: 13, level: 50)
Pokemon.create(name: "Cacturne", trainer_id: 11, type1_id: 3, type2_id: 13, level: 50)
Pokemon.create(name: "Sharpedo", trainer_id: 11, type1_id: 1, type2_id: 13, level: 50)
Pokemon.create(name: "Absol", trainer_id: 11, type1_id: 13, type2_id: nil, level: 52)

Pokemon.create(name: "Dusclops", trainer_id: 12, type1_id: 12, type2_id: nil, level: 51)
Pokemon.create(name: "Banette", trainer_id: 12, type1_id: 12, type2_id: nil, level: 51)
Pokemon.create(name: "Sableye", trainer_id: 12, type1_id: 12, type2_id: 13, level: 51)
Pokemon.create(name: "Banette", trainer_id: 12, type1_id: 12, type2_id: nil, level: 51)
Pokemon.create(name: "Dusknoir", trainer_id: 12, type1_id: 12, type2_id: nil, level: 53)

Pokemon.create(name: "Glalie", trainer_id: 13, type1_id: 16, type2_id: nil, level: 52)
Pokemon.create(name: "Frostlass", trainer_id: 13, type1_id: 16, type2_id: 12, level: 52)
Pokemon.create(name: "Glalie", trainer_id: 13, type1_id: 16, type2_id: nil, level: 52)
Pokemon.create(name: "Froslass", trainer_id: 13, type1_id: 16, type2_id: 12, level: 52)
Pokemon.create(name: "Walrein", trainer_id: 13, type1_id: 16, type2_id: 1, level: 54)

Pokemon.create(name: "Altaria", trainer_id: 14, type1_id: 8, type2_id: 4, level: 53)
Pokemon.create(name: "Flygon", trainer_id: 14, type1_id: 8, type2_id: 6, level: 53)
Pokemon.create(name: "Kingdra", trainer_id: 14, type1_id: 8, type2_id: 1, level: 53)
Pokemon.create(name: "Flygon", trainer_id: 14, type1_id: 8, type2_id: 6, level: 53)
Pokemon.create(name: "Salamence", trainer_id: 14, type1_id: 8, type2_id: 4, level: 55)

Pokemon.create(name: "Skarmory", trainer_id: 15, type1_id: 9, type2_id: 4, level: 57)
Pokemon.create(name: "Claydol", trainer_id: 15, type1_id: 6, type2_id: 11, level: 57)
Pokemon.create(name: "Aggron", trainer_id: 15, type1_id: 9, type2_id: 5, level: 57)
Pokemon.create(name: "Cradily", trainer_id: 15, type1_id: 3, type2_id: 5, level: 57)
Pokemon.create(name: "Armaldo", trainer_id: 15, type1_id: 5, type2_id: 15, level: 57)
Pokemon.create(name: "Metagross", trainer_id: 15, type1_id: 9, type2_id: 11, level: 59)

Pokemon.create(name: "Dustox", trainer_id: 16, type1_id: 15, type2_id: 18, level: 53)
Pokemon.create(name: "Beautifly", trainer_id: 16, type1_id: 15, type2_id: 4, level: 53)
Pokemon.create(name: "Vespiquen", trainer_id: 16, type1_id: 15, type2_id: 4, level: 54)
Pokemon.create(name: "Heracross", trainer_id: 16, type1_id: 15, type2_id: 7, level: 54)
Pokemon.create(name: "Drapion", trainer_id: 16, type1_id: 18, type2_id: 13, level: 57)

Pokemon.create(name: "Quagsire", trainer_id: 17, type1_id: 1, type2_id: 6, level: 55)
Pokemon.create(name: "Sudowoodo", trainer_id: 17, type1_id: 5, type2_id: nil, level: 56)
Pokemon.create(name: "Golem", trainer_id: 17, type1_id: 5, type2_id: 6, level: 56)
Pokemon.create(name: "Whiscash", trainer_id: 17, type1_id: 1, type2_id: 6, level: 55)
Pokemon.create(name: "Hippowdon", trainer_id: 17, type1_id: 6, type2_id: nil, level: 59)

Pokemon.create(name: "Rapidash", trainer_id: 18, type1_id: 2, type2_id: nil, level: 58)
Pokemon.create(name: "Steelix", trainer_id: 18, type1_id: 6, type2_id: 9, level: 57)
Pokemon.create(name: "Drifblim", trainer_id: 18, type1_id: 4, type2_id: 12, level: 58)
Pokemon.create(name: "Lopunny", trainer_id: 18, type1_id: 10, type2_id: nil, level: 57)
Pokemon.create(name: "Infernape", trainer_id: 18, type1_id: 2, type2_id: 7, level: 61)

Pokemon.create(name: "Mr. Mime", trainer_id: 19, type1_id: 11, type2_id: 17, level: 59)
Pokemon.create(name: "Girafarig", trainer_id: 19, type1_id: 11, type2_id: 10, level: 59)
Pokemon.create(name: "Medicham", trainer_id: 19, type1_id: 11, type2_id: 7, level: 60)
Pokemon.create(name: "Alakazam", trainer_id: 19, type1_id: 11, type2_id: nil, level: 60)
Pokemon.create(name: "Bronzong", trainer_id: 19, type1_id: 11, type2_id: 9, level: 63)

Pokemon.create(name: "Spiritomb", trainer_id: 20, type1_id: 12, type2_id: 13, level: 61)
Pokemon.create(name: "Roserade", trainer_id: 20, type1_id: 3, type2_id: 18, level: 60)
Pokemon.create(name: "Gastrodon", trainer_id: 20, type1_id: 1, type2_id: 6, level: 60)
Pokemon.create(name: "Lucario", trainer_id: 20, type1_id: 7, type2_id: 9, level: 63)
Pokemon.create(name: "Milotic", trainer_id: 20, type1_id: 1, type2_id: nil, level: 63)
Pokemon.create(name: "Garchomp", trainer_id: 20, type1_id: 8, type2_id: 6, level: 66)

Pokemon.create(name: "Cofagrigus", trainer_id: 21, type1_id: 12, type2_id: nil, level: 60)
Pokemon.create(name: "Drifblim", trainer_id: 21, type1_id: 12, type2_id: 4, level: 60)
Pokemon.create(name: "Golurk", trainer_id: 21, type1_id: 12, type2_id: 6, level: 60)
Pokemon.create(name: "Banette", trainer_id: 21, type1_id: 12, type2_id: nil, level: 60)
Pokemon.create(name: "Chandelure", trainer_id: 21, type1_id: 12, type2_id: 2, level: 62)

Pokemon.create(name: "Throh", trainer_id: 22, type1_id: 7, type2_id: nil, level: 60)
Pokemon.create(name: "Sawk", trainer_id: 22, type1_id: 7, type2_id: 18, level: 60)
Pokemon.create(name: "Mienshao", trainer_id: 22, type1_id: 7, type2_id: 6, level: 60)
Pokemon.create(name: "Lucario", trainer_id: 22, type1_id: 7, type2_id: 9, level: 60)
Pokemon.create(name: "Conkeldurr", trainer_id: 22, type1_id: 7, type2_id: nil, level: 62)

Pokemon.create(name: "Liepard", trainer_id: 23, type1_id: 13, type2_id: nil, level: 60)
Pokemon.create(name: "Scrafty", trainer_id: 23, type1_id: 13, type2_id: 7, level: 60)
Pokemon.create(name: "Krookodile", trainer_id: 23, type1_id: 13, type2_id: 6, level: 60)
Pokemon.create(name: "Absol", trainer_id: 23, type1_id: 13, type2_id: nil, level: 60)
Pokemon.create(name: "Bisharp", trainer_id: 23, type1_id: 13, type2_id: 9, level: 62)

Pokemon.create(name: "Musharna", trainer_id: 24, type1_id: 11, type2_id: nil, level: 60)
Pokemon.create(name: "Sigilyph", trainer_id: 24, type1_id: 11, type2_id: 4, level: 60)
Pokemon.create(name: "Reuniculus", trainer_id: 24, type1_id: 11, type2_id: nil, level: 60)
Pokemon.create(name: "Gothitelle", trainer_id: 24, type1_id: 11, type2_id: nil, level: 60)
Pokemon.create(name: "Metagross", trainer_id: 24, type1_id: 11, type2_id: 7, level: 62)

Pokemon.create(name: "Accelgor", trainer_id: 25, type1_id: 15, type2_id: nil, level: 75)
Pokemon.create(name: "Bouffalant", trainer_id: 25, type1_id: 10, type2_id: nil, level: 75)
Pokemon.create(name: "Druddigon", trainer_id: 25, type1_id: 8, type2_id: nil, level: 75)
Pokemon.create(name: "Vanilluxe", trainer_id: 25, type1_id: 16, type2_id: nil, level: 75)
Pokemon.create(name: "Escavalier", trainer_id: 25, type1_id: 15, type2_id: 9, level: 75)
Pokemon.create(name: "Volcarona", trainer_id: 25, type1_id: 15, type2_id: 2, level: 77)

Pokemon.create(name: "Pyroar", trainer_id: 26, type1_id: 2, type2_id: 10, level: 63)
Pokemon.create(name: "Torkoal", trainer_id: 26, type1_id: 2, type2_id: nil, level: 63)
Pokemon.create(name: "Chandelure", trainer_id: 26, type1_id: 2, type2_id: 12, level: 63)
Pokemon.create(name: "Talonflame", trainer_id: 26, type1_id: 2, type2_id: 4, level: 65)

Pokemon.create(name: "Clawitzer", trainer_id: 27, type1_id: 1, type2_id: nil, level: 63)
Pokemon.create(name: "Gyarados", trainer_id: 27, type1_id: 1, type2_id: 4, level: 63)
Pokemon.create(name: "Starmie", trainer_id: 27, type1_id: 1, type2_id: 11, level: 63)
Pokemon.create(name: "Barbabarcle", trainer_id: 27, type1_id: 1, type2_id: 5, level: 65)

Pokemon.create(name: "Klefki", trainer_id: 28, type1_id: 9, type2_id: 17, level: 63)
Pokemon.create(name: "Probopass", trainer_id: 28, type1_id: 9, type2_id: 5, level: 63)
Pokemon.create(name: "Scizor", trainer_id: 28, type1_id: 9, type2_id: 15, level: 63)
Pokemon.create(name: "Aegislash", trainer_id: 28, type1_id: 9, type2_id: 12, level: 65)

Pokemon.create(name: "Dragalge", trainer_id: 29, type1_id: 8, type2_id: 18, level: 63)
Pokemon.create(name: "Druddigon", trainer_id: 29, type1_id: 8, type2_id: nil, level: 63)
Pokemon.create(name: "Altaria", trainer_id: 29, type1_id: 8, type2_id: 4, level: 63)
Pokemon.create(name: "Noivern", trainer_id: 29, type1_id: 8, type2_id: 4, level: 65)

Pokemon.create(name: "Hawlucha", trainer_id: 30, type1_id: 4, type2_id: 7, level: 64)
Pokemon.create(name: "Tyrantrum", trainer_id: 30, type1_id: 8, type2_id: 5, level: 65)
Pokemon.create(name: "Aurorus", trainer_id: 30, type1_id: 16, type2_id: 5, level: 65)
Pokemon.create(name: "Gourgeist", trainer_id: 30, type1_id: 3, type2_id: 12, level: 65)
Pokemon.create(name: "Goodra", trainer_id: 30, type1_id: 8, type2_id: nil, level: 66)
Pokemon.create(name: "Gardevoir", trainer_id: 30, type1_id: 11, type2_id: 17, level: 68)

Pokemon.create(name: "Hariyama", trainer_id: 31, type1_id: 7, type2_id: nil, level: 54)
Pokemon.create(name: "Primeape", trainer_id: 31, type1_id: 7, type2_id: nil, level: 54)
Pokemon.create(name: "Bewear", trainer_id: 31, type1_id: 7, type2_id: 10, level: 54)
Pokemon.create(name: "Poliwrath", trainer_id: 31, type1_id: 1, type2_id: 7, level: 54)
Pokemon.create(name: "Crabominable", trainer_id: 31, type1_id: 7, type2_id: 16, level: 55)

Pokemon.create(name: "Armaldo", trainer_id: 32, type1_id: 5, type2_id: 15, level: 56)
Pokemon.create(name: "Cradily", trainer_id: 32, type1_id: 5, type2_id: 3, level: 56)
Pokemon.create(name: "Gigalith", trainer_id: 32, type1_id: 5, type2_id: nil, level: 56)
Pokemon.create(name: "Probopass", trainer_id: 32, type1_id: 5, type2_id: 9, level: 56)
Pokemon.create(name: "Lycanroc", trainer_id: 32, type1_id: 5, type2_id: nil, level: 57)

Pokemon.create(name: "Banette", trainer_id: 33, type1_id: 12, type2_id: nil, level: 56)
Pokemon.create(name: "Drifblim", trainer_id: 33, type1_id: 12, type2_id: 4, level: 56)
Pokemon.create(name: "Dhelmise", trainer_id: 33, type1_id: 12, type2_id: 3, level: 56)
Pokemon.create(name: "Froslass", trainer_id: 33, type1_id: 12, type2_id: 16, level: 56)
Pokemon.create(name: "Palossand", trainer_id: 33, type1_id: 12, type2_id: 6, level: 57)

Pokemon.create(name: "Braviary", trainer_id: 34, type1_id: 10, type2_id: 4, level: 56)
Pokemon.create(name: "Hawlucha", trainer_id: 34, type1_id: 4, type2_id: 7, level: 56)
Pokemon.create(name: "Oricorio", trainer_id: 34, type1_id: 4, type2_id: 2, level: 56)
Pokemon.create(name: "Mandibuzz", trainer_id: 34, type1_id: 4, type2_id: 13, level: 56)
Pokemon.create(name: "Toucannon", trainer_id: 34, type1_id: 10, type2_id: 4, level: 57)

Pokemon.create(name: "Lycanroc", trainer_id: 35, type1_id: 5, type2_id: nil, level: 57)
Pokemon.create(name: "Ninetales", trainer_id: 35, type1_id: 16, type2_id: 17, level: 56)
Pokemon.create(name: "Braviary", trainer_id: 35, type1_id: 4, type2_id: 10, level: 56)
Pokemon.create(name: "Magnezone", trainer_id: 35, type1_id: 9, type2_id: 14, level: 56)
Pokemon.create(name: "Snorlax", trainer_id: 35, type1_id: 10, type2_id: nil, level: 56)
Pokemon.create(name: "Decidueye", trainer_id: 35, type1_id: 3, type2_id: 12, level: 58)

puts "✅ Done seeding!"
