




Trainer.create(name: "Lorelei", region: "Kanto", title: "First", trainer_type: "ICE", avatar_url:"pokemonImages/dewgong.png", likes: 5)
Trainer.create(name: "Bruno", region: "Kanto", title: "Second", trainer_type: "FIGHTING", avatar_url:"///6/64/VSBruno_PE.png/100px-VSBruno_PE.png", likes: 8)
Trainer.create(name: "Agatha", region: "Kanto", title: "Third", trainer_type:"GHOST", avatar_url:"https://archives.bulbagarden.net/media/upload/5/5f/VSAgatha_PE.png", likes:2)
Trainer.create(name: "Lance", region: "Kanto", title: "Fourth", trainer_type:"DRAGON", avatar_url:"https://archives.bulbagarden.net/media/upload/d/dc/VSLance_PE.png", likes: 10)
Trainer.create(name: "Blue", region: "Kanto", title: "Champion", trainer_type:nil, avatar_url:"https://archives.bulbagarden.net/media/upload/1/1a/Lets_Go_Pikachu_Eevee_Blue.png", likes: 12)

Trainer.create(name: "Will", region: "Johto", title: "First", trainer_type:"PSYCHIC",avatar_url:"https://archives.bulbagarden.net/media/upload/0/07/VSWill.png", likes:20)
Trainer.create(name: "Koga", region: "Johto", title: "Second", trainer_type:"POISON",avatar_url:"https://archives.bulbagarden.net/media/upload/b/b0/VSKoga.png", likes:4)
Trainer.create(name: "Bruno", region: "Johto", title: "Third", trainer_type:"FIGHTING",avatar_url:"https://archives.bulbagarden.net/media/upload/b/b8/VSBruno.png", likes: 12)
Trainer.create(name: "Karen", region: "Johto", title: "Fourth", trainer_type:"DARK",avatar_url:"https://archives.bulbagarden.net/media/upload/f/f3/VSKaren.png", likes:35)
Trainer.create(name: "Lance", region: "Johto", title: "Champion", trainer_type:"DRAGON",avatar_url: "https://archives.bulbagarden.net/media/upload/c/cd/Lets_Go_Pikachu_Eevee_Lance.png", likes:40)

Trainer.create(name: "Sidney", region: "Hoenn", title: "First", trainer_type:"DARK",avatar_url:"https://archives.bulbagarden.net/media/upload/4/40/VSSidney.png", likes:10)
Trainer.create(name: "Phoebe", region: "Hoenn", title: "Second", trainer_type:"GHOST",avatar_url:"https://archives.bulbagarden.net/media/upload/0/01/VSPhoebe.png", likes:20)
Trainer.create(name: "Glacia", region: "Hoenn", title: "Third", trainer_type:"ICE",avatar_url:"https://archives.bulbagarden.net/media/upload/6/61/VSGlacia.png", likes:23)
Trainer.create(name: "Drake", region: "Hoenn", title: "Fourth", trainer_type:"DRAGON",avatar_url:"https://archives.bulbagarden.net/media/upload/f/f5/VSDrake.png", likes:54)
Trainer.create(name: "Steven", region: "Hoenn", title: "Champion", trainer_type:"STEEL",avatar_url:"https://archives.bulbagarden.net/media/upload/3/3f/Omega_Ruby_Alpha_Sapphire_Steven.png", likes:123)

Trainer.create(name: "Aaron", region: "Sinnoh", title: "First", trainer_type:"BUG",avatar_url:"https://archives.bulbagarden.net/media/upload/4/4d/VSAaron_BDSP.png", likes:45)
Trainer.create(name: "Bertha", region: "Sinnoh", title: "Second", trainer_type:"GROUND",avatar_url:"https://archives.bulbagarden.net/media/upload/a/a2/VSBertha_BDSP.png", likes:1)
Trainer.create(name: "Flint", region: "Sinnoh", title: "Third", trainer_type:"FIRE",avatar_url:"https://archives.bulbagarden.net/media/upload/7/71/VSFlint_BDSP.png", likes: 15)
Trainer.create(name: "Lucian", region: "Sinnoh", title: "Fourth", trainer_type:"PSYCHIC",avatar_url:"https://archives.bulbagarden.net/media/upload/b/b4/VSLucian_BDSP.png", likes: 22)
Trainer.create(name: "Cynthia", region: "Sinnoh", title: "Champion", trainer_type:nil,avatar_url:"https://archives.bulbagarden.net/media/upload/b/b3/Cynthia_JN.png", likes:39)

Trainer.create(name: "Shauntal", region: "Unova", title: "First", trainer_type:"GHOST", avatar_url:"https://archives.bulbagarden.net/media/upload/b/bf/Black_White_Shauntal.png", likes:43)
Trainer.create(name: "Marshal", region: "Unova", title: "Second", trainer_type:"FIGHTING", avatar_url:"https://static.wikia.nocookie.net/pokemon/images/b/b9/Marshal.png/revision/latest?cb=20151220160341", likes:3)
Trainer.create(name: "Grimsley", region: "Unova", title: "Third", trainer_type:"DARK", avatar_url:"https://static.wikia.nocookie.net/pokemon/images/a/a0/Grimsley_Masters.png/revision/latest/scale-to-width-down/180?cb=20200525151207", likes:12)
Trainer.create(name: "Caitlin", region: "Unova", title: "Fourth", trainer_type:"PSYCHIC", avatar_url:"https://static.wikia.nocookie.net/pokemon/images/4/4c/Caitlin_Platinum.png/revision/latest?cb=20151213220555", likes:45)
Trainer.create(name: "Alder", region: "Unova", title: "Champion", trainer_type:nil, avatar_url:"https://www.serebii.net/pokemonmasters/syncpairs/alder.png", likes:43)

Trainer.create(name: "Malva", region: "Kalos", title: "First", trainer_type:"FIRE", avatar_url:"https://static.wikia.nocookie.net/pokemon/images/8/8b/Malva.png/revision/latest?cb=20140717160108", likes: 6)
Trainer.create(name: "Siebold", region: "Kalos", title: "Second", trainer_type:"WATER", avatar_url:"https://static.wikia.nocookie.net/pokemon/images/6/6c/Siebold.png/revision/latest?cb=20140717155318", likes:32)
Trainer.create(name: "Wikstrom", region: "Kalos", title: "Third", trainer_type:"STEEL", avatar_url:"https://www.serebii.net/pokemonmasters/syncpairs/wikstrom.png", likes: 45)
Trainer.create(name: "Drasna", region: "Kalos", title: "Fourth", trainer_type:"DRAGON", avatar_url:"https://i.pinimg.com/736x/fd/01/7d/fd017d730d9b73c8457789fd9e9113d7.jpg", likes:65)
Trainer.create(name: "Diantha", region: "Kalos", title: "Champion", trainer_type:nil, avatar_url:"https://www.serebii.net/pokemonmasters/syncpairs/diantha.png", likes:98)

Trainer.create(name: "Hala", region: "Aloha", title: "First", trainer_type:"FIGHTING", avatar_url:"https://www.serebii.net/pokemonmasters/syncpairs/hala.png", likes:34)
Trainer.create(name: "Olivia", region: "Aloha", title: "Second", trainer_type:"ROCK", avatar_url:"https://carboncostume.com/wordpress/wp-content/uploads/2017/02/oliviafrompokemonsunandmoon.jpg", likes:65)
Trainer.create(name: "Acerola", region: "Aloha", title: "Third", trainer_type:"GHOST", avatar_url:"https://static.wikia.nocookie.net/pokemon/images/f/fa/Acerola_Masters.png/revision/latest/scale-to-width-down/250?cb=20191020205231", likes:32)
Trainer.create(name: "Kahili", region: "Aloha", title: "Fourth", trainer_type:"FLYING", avatar_url:"https://www.serebii.net/pokemonmasters/syncpairs/kahili.png", likes:55)
Trainer.create(name: "Kukui", region: "Aloha", title: "Champion", trainer_type:nil, avatar_url:"https://static.wikia.nocookie.net/adventures-of-chris-and-tifa/images/0/0b/47F72A59-FD96-4DC2-8E4E-94C666628986.png/revision/latest?cb=20201212160614", likes:32)

Pokemon.create(name: "Dewgong", trainer_id: 1, type1_id:"WATER", type2_id:"ICE", level: 51, avatar_url:"pokemonImages/dewgong.png")
Pokemon.create(name: "Jynx", trainer_id: 1, type1_id:"PSYCHIC", type2_id:"ICE", level: 51, avatar_url:"pokemonImages/jynx.png")
Pokemon.create(name: "Cloyster", trainer_id: 1, type1_id:"WATER", type2_id:"ICE", level: 51, avatar_url:"pokemonImages/cloyster.png")
Pokemon.create(name: "Slowbro", trainer_id: 1, type1_id:"WATER", type2_id:"PSYCHIC", level: 51, avatar_url:"pokemonImages/slowbro.png")
Pokemon.create(name: "Lapras", trainer_id: 1, type1_id:"WATER", type2_id:"ICE", level: 52, avatar_url:"pokemonImages/lapras.png")

Pokemon.create(name: "Onyx", trainer_id: 2, type1_id:"ROCK", type2_id:"GROUND", level: 52, avatar_url:"pokemonImages/onyx.png")
Pokemon.create(name: "Hitmonchan", trainer_id: 2, type1_id:"PSYCHIC", type2_id:"ICE", level: 52, avatar_url:"pokemonImages/hitmonchan.png")
Pokemon.create(name: "Hitmonlee", trainer_id: 2, type1_id:"FIGHTING", type2_id: nil, level: 52, avatar_url:"pokemonImages/hitmonlee.png")
Pokemon.create(name: "Poliwrath", trainer_id: 2, type1_id:"WATER", type2_id:"FIGHTING", level: 52, avatar_url:"pokemonImages/poliwrath.png")
Pokemon.create(name: "Machamp", trainer_id: 2, type1_id:"FIGHTING", type2_id: nil, level: 53, avatar_url:"pokemonImages/machamp.png")

Pokemon.create(name: "Arbok", trainer_id: 3, type1_id:"POISON", type2_id: nil, level: 53, avatar_url:"pokemonImages/arbok.png")
Pokemon.create(name: "Gengar", trainer_id: 3, type1_id:"GHOST", type2_id:"POISON", level: 53, avatar_url:"pokemonImages/gengar.png")
Pokemon.create(name: "Golbat", trainer_id: 3, type1_id:"POISON", type2_id:"FLYING", level: 53, avatar_url:"pokemonImages/golbat.png")
Pokemon.create(name: "Weezing", trainer_id: 3, type1_id:"POISON", type2_id: nil, level: 53, avatar_url:"pokemonImages/weezing.png")
Pokemon.create(name: "Gengar", trainer_id: 3, type1_id:"GHOST", type2_id:"POISON", level: 54, avatar_url:"pokemonImages/gengar.png")

Pokemon.create(name: "Seadra", trainer_id: 4, type1_id:"WATER", type2_id: nil, level: 54, avatar_url:"pokemonImages/seadra.png")
Pokemon.create(name: "Aerodactyl", trainer_id: 4, type1_id:"FLYING", type2_id:"ROCK", level: 54, avatar_url:"pokemonImages/aerodactyl.png")
Pokemon.create(name: "Gyarados", trainer_id: 4, type1_id:"WATER", type2_id:"FLYING", level: 54, avatar_url:"pokemonImages/gyarados.png")
Pokemon.create(name: "Charizard", trainer_id: 4, type1_id:"FIRE", type2_id:"FLYING", level: 54, avatar_url:"pokemonImages/charizard.png")
Pokemon.create(name: "Dragonite", trainer_id: 4, type1_id:"DRAGON", type2_id:"FLYING", level: 55, avatar_url:"pokemonImages/dragonite.png")

Pokemon.create(name: "Heracross", trainer_id: 5, type1_id:"FIGHTING", type2_id:"BUG", level: 72, avatar_url:"pokemonImages/heracross.png")
Pokemon.create(name: "Alakazam", trainer_id: 5, type1_id:"PSYCHIC", type2_id: nil, level: 73, avatar_url:"pokemonImages/alakazam.png")
Pokemon.create(name: "Tyranitar", trainer_id: 5, type1_id:"ROCK", type2_id:"DARK", level: 72, avatar_url:"pokemonImages/tyranitar.png")
Pokemon.create(name: "Gyarados", trainer_id: 5, type1_id:"WATER", type2_id:"FLYING", level: 73, avatar_url:"pokemonImages/gyarados.png")
Pokemon.create(name: "Arcanine", trainer_id: 5, type1_id:"FIRE", type2_id: nil, level: 73, avatar_url:"pokemonImages/arcanine.png")
Pokemon.create(name: "Venusaur", trainer_id: 5, type1_id:"GRASS", type2_id:"POISON", level: 75, avatar_url:"pokemonImages/venusaur.png")

Pokemon.create(name: "Xatu", trainer_id: 6, type1_id:"FLYING", type2_id:"PSYCHIC", level: 40, avatar_url:"pokemonImages/xatu.png")
Pokemon.create(name: "Jynx", trainer_id: 6, type1_id:"ICE", type2_id:"PSYCHIC", level: 41, avatar_url:"pokemonImages/jynx.png")
Pokemon.create(name: "Slowbro", trainer_id: 6, type1_id:"WATER", type2_id:"PSYCHIC", level: 41, avatar_url:"pokemonImages/slowbro.png")
Pokemon.create(name: "Exeggutor", trainer_id: 6, type1_id:"GRASS", type2_id:"PSYCHIC", level: 41, avatar_url:"pokemonImages/exeggutor.png")
Pokemon.create(name: "Xatu", trainer_id: 6, type1_id:"FLYING", type2_id:"PSYCHIC", level: 42, avatar_url:"pokemonImages/xatu.png")

Pokemon.create(name: "Ariados", trainer_id: 7, type1_id:"BUG", type2_id:"POISON", level: 40, avatar_url:"pokemonImages/ariados.png")
Pokemon.create(name: "Forretress", trainer_id: 7, type1_id:"BUG", type2_id:"DRAGON", level: 43, avatar_url:"pokemonImages/forretress.png")
Pokemon.create(name: "Muk", trainer_id: 7, type1_id:"POISON", type2_id: nil, level: 42, avatar_url:"pokemonImages/muk.png")
Pokemon.create(name: "Venomoth", trainer_id: 7, type1_id:"BUG", type2_id:"POISON", level: 41, avatar_url:"pokemonImages/venomoth.png")
Pokemon.create(name: "Crobat", trainer_id: 7, type1_id:"FLYING", type2_id:"POISON", level: 44, avatar_url:"pokemonImages/crobat.png")

Pokemon.create(name: "Hitmontop", trainer_id: 8, type1_id:"FIGHTING", type2_id: nil, level: 42, avatar_url:"pokemonImages/hitmontop.png")
Pokemon.create(name: "Hitmonlee", trainer_id: 8, type1_id:"FIGHTING", type2_id: nil, level: 42, avatar_url:"pokemonImages/hitmonlee.png")
Pokemon.create(name: "Hitmonchan", trainer_id: 8, type1_id:"FIGHTING", type2_id: nil, level: 42, avatar_url:"pokemonImages/hitmonchan.png")
Pokemon.create(name: "Onyx", trainer_id: 8, type1_id:"ROCK", type2_id:"GROUND", level: 43, avatar_url:"pokemonImages/onyx.png")
Pokemon.create(name: "Machamp", trainer_id: 8, type1_id:"FIGHTING", type2_id: nil, level: 46, avatar_url:"pokemonImages/machamp.png")

Pokemon.create(name: "Umbreon", trainer_id: 9, type1_id:"DARK", type2_id: nil, level: 42, avatar_url:"pokemonImages/umbreon.png")
Pokemon.create(name: "Vileplume", trainer_id: 9, type1_id:"GRASS", type2_id:"POISON", level: 42, avatar_url:"pokemonImages/vileplume.png")
Pokemon.create(name: "Murkrow", trainer_id: 9, type1_id:"FLYING", type2_id:"DARK", level: 44, avatar_url:"pokemonImages/murkrow.png")
Pokemon.create(name: "Gengar", trainer_id: 9, type1_id:"POISON", type2_id:"GHOST", level: 45, avatar_url:"pokemonImages/gengar.png")
Pokemon.create(name: "Houndoom", trainer_id: 9, type1_id:"FIRE", type2_id:"DARK", level: 47, avatar_url:"pokemonImages/houndoom.png")

Pokemon.create(name: "Gyarados", trainer_id: 10, type1_id:"FLYING", type2_id:"WATER", level: 44, avatar_url:"pokemonImages/gyarados.png")
Pokemon.create(name: "Dragonite", trainer_id: 10, type1_id:"FLYING", type2_id:"DRAGON", level: 49, avatar_url:"pokemonImages/dragonite.png")
Pokemon.create(name: "Dragonite", trainer_id: 10, type1_id:"FLYING", type2_id:"DRAGON", level: 49, avatar_url:"pokemonImages/dragonite.png")
Pokemon.create(name: "Aerodactyl", trainer_id: 10, type1_id:"FLYING", type2_id:"ROCK", level: 48, avatar_url:"pokemonImages/aerodactyl.png")
Pokemon.create(name: "Charizard", trainer_id: 10, type1_id:"FLYING", type2_id:"FIRE", level: 48, avatar_url: "pokemonImages/charizard.png")
Pokemon.create(name: "Dragonite", trainer_id: 10, type1_id:"FLYING", type2_id:"DRAGON", level: 50, avatar_url:"pokemonImages/dragonite.png")

Pokemon.create(name: "Mightyena", trainer_id: 11, type1_id:"DARK", type2_id: nil, level: 50, avatar_url:"pokemonImages/mightyena.png")
Pokemon.create(name: "Shiftry", trainer_id: 11, type1_id:"GRASS", type2_id:"DARK", level: 50, avatar_url:"pokemonImages/shiftry.png")
Pokemon.create(name: "Cacturne", trainer_id: 11, type1_id:"GRASS", type2_id:"DARK", level: 50, avatar_url:"pokemonImages/cacturne.png")
Pokemon.create(name: "Sharpedo", trainer_id: 11, type1_id:"WATER", type2_id:"DARK", level: 50, avatar_url:"pokemonImages/sharpedo.png")
Pokemon.create(name: "Absol", trainer_id: 11, type1_id:"DARK", type2_id: nil, level: 52, avatar_url:"pokemonImages/absol.png")

Pokemon.create(name: "Dusclops", trainer_id: 12, type1_id:"GHOST", type2_id: nil, level: 51, avatar_url:"pokemonImages/dusclops.png")
Pokemon.create(name: "Banette", trainer_id: 12, type1_id:"GHOST", type2_id: nil, level: 51, avatar_url:"pokemonImages/banette.png")
Pokemon.create(name: "Sableye", trainer_id: 12, type1_id:"GHOST", type2_id:"DARK", level: 51, avatar_url:"pokemonImages/sableye.png")
Pokemon.create(name: "Banette", trainer_id: 12, type1_id:"GHOST", type2_id: nil, level: 51, avatar_url:"pokemonImages/banette.png")
Pokemon.create(name: "Dusknoir", trainer_id: 12, type1_id:"GHOST", type2_id: nil, level: 53, avatar_url:"pokemonImages/dusknoir.png")

Pokemon.create(name: "Glalie", trainer_id: 13, type1_id:"ICE", type2_id: nil, level: 52, avatar_url:"pokemonImages/glalie.png")
Pokemon.create(name: "Froslass", trainer_id: 13, type1_id:"ICE", type2_id:"GHOST", level: 52, avatar_url:"pokemonImages/froslass.png")
Pokemon.create(name: "Glalie", trainer_id: 13, type1_id:"ICE", type2_id: nil, level: 52, avatar_url:"pokemonImages/glalie.png")
Pokemon.create(name: "Froslass", trainer_id: 13, type1_id:"ICE", type2_id:"GHOST", level: 52, avatar_url:"pokemonImages/froslass.png")
Pokemon.create(name: "Walrein", trainer_id: 13, type1_id:"ICE", type2_id:"WATER", level: 54, avatar_url:"pokemonImages/walrein.png")

Pokemon.create(name: "Altaria", trainer_id: 14, type1_id:"DRAGON", type2_id:"FLYING", level: 53, avatar_url:"pokemonImages/altaria.png")
Pokemon.create(name: "Flygon", trainer_id: 14, type1_id:"DRAGON", type2_id:"GROUND", level: 53, avatar_url:"pokemonImages/flygon.png")
Pokemon.create(name: "Kingdra", trainer_id: 14, type1_id:"DRAGON", type2_id:"WATER", level: 53, avatar_url:"pokemonImages/kingdra.png")
Pokemon.create(name: "Flygon", trainer_id: 14, type1_id:"DRAGON", type2_id:"GROUND", level: 53, avatar_url:"pokemonImages/flygon.png")
Pokemon.create(name: "Salamence", trainer_id: 14, type1_id:"DRAGON", type2_id:"FLYING", level: 55,avatar_url:"pokemonImages/salamence.png")

Pokemon.create(name: "Skarmory", trainer_id: 15, type1_id:9, type2_id:"FLYING", level: 57, avatar_url:"pokemonImages/skarmory.png")
Pokemon.create(name: "Claydol", trainer_id: 15, type1_id:"GROUND", type2_id:"PSYCHIC", level: 57, avatar_url:"pokemonImages/claydol.png")
Pokemon.create(name: "Aggron", trainer_id: 15, type1_id:9, type2_id:"ROCK", level: 57, avatar_url:"pokemonImages/aggron.png")
Pokemon.create(name: "Cradily", trainer_id: 15, type1_id:"GRASS", type2_id:"ROCK", level: 57, avatar_url:"pokemonImages/cradily.png")
Pokemon.create(name: "Armaldo", trainer_id: 15, type1_id:"ROCK", type2_id:"BUG", level: 57, avatar_url:"pokemonImages/armaldo.png")
Pokemon.create(name: "Metagross", trainer_id: 15, type1_id:9, type2_id:"PSYCHIC", level: 59, avatar_url:"pokemonImages/metagross.png")

Pokemon.create(name: "Dustox", trainer_id: 16, type1_id:"BUG", type2_id:"POISON", level: 53, avatar_url:"pokemonImages/dustox.png")
Pokemon.create(name: "Beautifly", trainer_id: 16, type1_id:"BUG", type2_id:"FLYING", level: 53, avatar_url:"pokemonImages/beautifly.png")
Pokemon.create(name: "Vespiquen", trainer_id: 16, type1_id:"BUG", type2_id:"FLYING", level: 54, avatar_url:"pokemonImages/vespiquen.png")
Pokemon.create(name: "Heracross", trainer_id: 16, type1_id:"BUG", type2_id:"FIGHTING", level: 54, avatar_url:"pokemonImages/heracross.png")
Pokemon.create(name: "Drapion", trainer_id: 16, type1_id:"POISON", type2_id:"DARK", level: 57, avatar_url:"pokemonImages/drapion.png")

Pokemon.create(name: "Quagsire", trainer_id: 17, type1_id:"WATER", type2_id:"GROUND", level: 55, avatar_url:"pokemonImages/quagsire.png")
Pokemon.create(name: "Sudowoodo", trainer_id: 17, type1_id:"ROCK", type2_id: nil, level: 56, avatar_url:"pokemonImages/sudowoodo.png")
Pokemon.create(name: "Golem", trainer_id: 17, type1_id:"ROCK", type2_id:"GROUND", level: 56, avatar_url:"pokemonImages/golem.png")
Pokemon.create(name: "Whiscash", trainer_id: 17, type1_id:"WATER", type2_id:"GROUND", level: 55, avatar_url:"pokemonImages/whiscash.png")
Pokemon.create(name: "Hippowdon", trainer_id: 17, type1_id:"GROUND", type2_id: nil, level: 59, avatar_url:"pokemonImages/hippowdon.png")

Pokemon.create(name: "Rapidash", trainer_id: 18, type1_id:"FIRE", type2_id: nil, level: 58, avatar_url:"pokemonImages/rapidash.png")
Pokemon.create(name: "Steelix", trainer_id: 18, type1_id:"GROUND", type2_id:"DRAGON", level: 57, avatar_url:"pokemonImages/steelix.png")
Pokemon.create(name: "Drifblim", trainer_id: 18, type1_id:"FLYING", type2_id:"GHOST", level: 58, avatar_url:"pokemonImages/drifblim.png")
Pokemon.create(name: "Lopunny", trainer_id: 18, type1_id:"NORMAL", type2_id: nil, level: 57, avatar_url:"pokemonImages/lopunny.png")
Pokemon.create(name: "Infernape", trainer_id: 18, type1_id:"FIRE", type2_id:"FIGHTING", level: 61, avatar_url:"pokemonImages/infernape.png")

Pokemon.create(name: "Mr. Mime", trainer_id: 19, type1_id:"PSYCHIC", type2_id:"FAIRY", level: 59, avatar_url:"pokemonImages/mr_mime.png")
Pokemon.create(name: "Girafarig", trainer_id: 19, type1_id:"PSYCHIC", type2_id:"NORMAL", level: 59, avatar_url:"pokemonImages/girafarig.png")
Pokemon.create(name: "Medicham", trainer_id: 19, type1_id:"PSYCHIC", type2_id:"FIGHTING", level: 60, avatar_url:"pokemonImages/medicham.png")
Pokemon.create(name: "Alakazam", trainer_id: 19, type1_id:"PSYCHIC", type2_id: nil, level: 60, avatar_url:"pokemonImages/alakazam.png")
Pokemon.create(name: "Bronzong", trainer_id: 19, type1_id:"PSYCHIC", type2_id:"DRAGON", level: 63, avatar_url:"pokemonImages/bronzong.png")

Pokemon.create(name: "Spiritomb", trainer_id: 20, type1_id:"GHOST", type2_id:"DARK", level: 61, avatar_url:"pokemonImages/spiritomb.png")
Pokemon.create(name: "Roserade", trainer_id: 20, type1_id:"GRASS", type2_id:"POISON", level: 60, avatar_url:"pokemonImages/roserade.png")
Pokemon.create(name: "Gastrodon", trainer_id: 20, type1_id:"WATER", type2_id:"GROUND", level: 60, avatar_url:"pokemonImages/gastrodon.png")
Pokemon.create(name: "Lucario", trainer_id: 20, type1_id:"FIGHTING", type2_id:"DRAGON", level: 63, avatar_url:"pokemonImages/lucario.png")
Pokemon.create(name: "Milotic", trainer_id: 20, type1_id:"WATER", type2_id: nil, level: 63, avatar_url:"pokemonImages/milotic.png")
Pokemon.create(name: "Garchomp", trainer_id: 20, type1_id:"DRAGON", type2_id:"GROUND", level: 66, avatar_url:"pokemonImages/garchomp.png")

Pokemon.create(name: "Cofagrigus", trainer_id: 21, type1_id:"GHOST", type2_id: nil, level: 60, avatar_url:"pokemonImages/cofagrigus.png")
Pokemon.create(name: "Drifblim", trainer_id: 21, type1_id:"GHOST", type2_id:"FLYING", level: 60, avatar_url:"pokemonImages/drifblim.png")
Pokemon.create(name: "Golurk", trainer_id: 21, type1_id:"GHOST", type2_id:"GROUND", level: 60, avatar_url:"pokemonImages/golurk.png")
Pokemon.create(name: "Banette", trainer_id: 21, type1_id:"GHOST", type2_id: nil, level: 60, avatar_url:"pokemonImages/banette.png")
Pokemon.create(name: "Chandelure", trainer_id: 21, type1_id:"GHOST", type2_id:"FIRE", level: 62, avatar_url:"pokemonImages/chandelure.png")

Pokemon.create(name: "Throh", trainer_id: 22, type1_id:"FIGHTING", type2_id: nil, level: 60, avatar_url:"pokemonImages/throh.png")
Pokemon.create(name: "Sawk", trainer_id: 22, type1_id:"FIGHTING", type2_id:"POISON", level: 60, avatar_url:"pokemonImages/sawk.png")
Pokemon.create(name: "Mienshao", trainer_id: 22, type1_id:"FIGHTING", type2_id:"GROUND", level: 60, avatar_url:"pokemonImages/mienshao.png")
Pokemon.create(name: "Lucario", trainer_id: 22, type1_id:"FIGHTING", type2_id:"DRAGON", level: 60, avatar_url:"pokemonImages/lucario.png")
Pokemon.create(name: "Conkeldurr", trainer_id: 22, type1_id:"FIGHTING", type2_id: nil, level: 62, avatar_url:"pokemonImages/conkeldurr.png")

Pokemon.create(name: "Liepard", trainer_id: 23, type1_id:"DARK", type2_id: nil, level: 60, avatar_url:"pokemonImages/liepard.png")
Pokemon.create(name: "Scrafty", trainer_id: 23, type1_id:"DARK", type2_id:"FIGHTING", level: 60, avatar_url:"pokemonImages/scrafty.png")
Pokemon.create(name: "Krookodile", trainer_id: 23, type1_id:"DARK", type2_id:"GROUND", level: 60, avatar_url:"pokemonImages/krookodile.png")
Pokemon.create(name: "Absol", trainer_id: 23, type1_id:"DARK", type2_id: nil, level: 60, avatar_url:"pokemonImages/absol.png")
Pokemon.create(name: "Bisharp", trainer_id: 23, type1_id: "STEEL", type2_id:"DARK", level: 62, avatar_url:"pokemonImages/bisharp.png")

Pokemon.create(name: "Musharna", trainer_id: 24, type1_id:"PSYCHIC", type2_id: nil, level: 60, avatar_url:"pokemonImages/musharna.png")
Pokemon.create(name: "Sigilyph", trainer_id: 24, type1_id:"PSYCHIC", type2_id:"FLYING", level: 60, avatar_url:"pokemonImages/sigilyph.png")
Pokemon.create(name: "Reuniculus", trainer_id: 24, type1_id:"PSYCHIC", type2_id: nil, level: 60, avatar_url:"pokemonImages/reuniculus.png")
Pokemon.create(name: "Gothitelle", trainer_id: 24, type1_id:"PSYCHIC", type2_id: nil, level: 60, avatar_url:"pokemonImages/gothitelle.png")
Pokemon.create(name: "Metagross", trainer_id: 24, type1_id:"PSYCHIC", type2_id:"FIGHTING", level: 62, avatar_url:"pokemonImages/metagross.png")

Pokemon.create(name: "Accelgor", trainer_id: 25, type1_id:"BUG", type2_id: nil, level: 75, avatar_url:"pokemonImages/accelgor.png")
Pokemon.create(name: "Bouffalant", trainer_id: 25, type1_id:"NORMAL", type2_id: nil, level: 75, avatar_url:"pokemonImages/bouffalant.png")
Pokemon.create(name: "Druddigon", trainer_id: 25, type1_id:"DRAGON", type2_id: nil, level: 75, avatar_url:"pokemonImages/druddigon.png")
Pokemon.create(name: "Vanilluxe", trainer_id: 25, type1_id:"ICE", type2_id: nil, level: 75, avatar_url:"pokemonImages/vanilluxe.png")
Pokemon.create(name: "Escavalier", trainer_id: 25, type1_id:"BUG", type2_id:"DRAGON", level: 75, avatar_url:"pokemonImages/escavalier.png")
Pokemon.create(name: "Volcarona", trainer_id: 25, type1_id:"BUG", type2_id:"FIRE", level: 77, avatar_url:"pokemonImages/volcarona.png")

Pokemon.create(name: "Pyroar", trainer_id: 26, type1_id:"FIRE", type2_id:"NORMAL", level: 63, avatar_url:"pokemonImages/pyroar.png")
Pokemon.create(name: "Torkoal", trainer_id: 26, type1_id:"FIRE", type2_id: nil, level: 63, avatar_url:"pokemonImages/torkoal.png")
Pokemon.create(name: "Chandelure", trainer_id: 26, type1_id:"FIRE", type2_id:"GHOST", level: 63, avatar_url:"pokemonImages/chandelure.png")
Pokemon.create(name: "Talonflame", trainer_id: 26, type1_id:"FIRE", type2_id:"FLYING", level: 65, avatar_url:"pokemonImages/talonflame.png")

Pokemon.create(name: "Clawitzer", trainer_id: 27, type1_id:"WATER", type2_id: nil, level: 63, avatar_url:"pokemonImages/clawitzer.png")
Pokemon.create(name: "Gyarados", trainer_id: 27, type1_id:"WATER", type2_id:"FLYING", level: 63, avatar_url:"pokemonImages/gyarados.png")
Pokemon.create(name: "Starmie", trainer_id: 27, type1_id:"WATER", type2_id:"PSYCHIC", level: 63, avatar_url:"pokemonImages/starmie.png")
Pokemon.create(name: "Barbabarcle", trainer_id: 27, type1_id:"WATER", type2_id:"ROCK", level: 65, avatar_url:"pokemonImages/barbaracle.png")

Pokemon.create(name: "Klefki", trainer_id: 28, type1_id:"ICE", type2_id:"FAIRY", level: 63, avatar_url:"pokemonImages/klefki.png")
Pokemon.create(name: "Probopass", trainer_id: 28, type1_id:"ICE", type2_id:"ROCK", level: 63, avatar_url:"pokemonImages/probopass.png")
Pokemon.create(name: "Scizor", trainer_id: 28, type1_id:"ICE", type2_id:"BUG", level: 63, avatar_url:"pokemonImages/scizor.png")
Pokemon.create(name: "Aegislash", trainer_id: 28, type1_id:"ICE", type2_id:"GHOST", level: 65, avatar_url:"pokemonImages/aegislash.png")

Pokemon.create(name: "Dragalge", trainer_id: 29, type1_id:"DRAGON", type2_id:"POISON", level: 63, avatar_url:"pokemonImages/dragalge.png")
Pokemon.create(name: "Druddigon", trainer_id: 29, type1_id:"DRAGON", type2_id: nil, level: 63, avatar_url:"pokemonImages/druddigon.png")
Pokemon.create(name: "Altaria", trainer_id: 29, type1_id:"DRAGON", type2_id:"FLYING", level: 63, avatar_url:"pokemonImages/altaria.png")
Pokemon.create(name: "Noivern", trainer_id: 29, type1_id:"DRAGON", type2_id:"FLYING", level: 65, avatar_url:"pokemonImages/noivern.png")

Pokemon.create(name: "Hawlucha", trainer_id: 30, type1_id:"FLYING", type2_id:"FIGHTING", level: 64, avatar_url:"pokemonImages/hawlucha.png")
Pokemon.create(name: "Tyrantrum", trainer_id: 30, type1_id:"DRAGON", type2_id:"ROCK", level: 65, avatar_url:"pokemonImages/tyrantrum.png")
Pokemon.create(name: "Aurorus", trainer_id: 30, type1_id:"ICE", type2_id:"ROCK", level: 65, avatar_url:"pokemonImages/aurorus.png")
Pokemon.create(name: "Gourgeist", trainer_id: 30, type1_id:"GRASS", type2_id:"GHOST", level: 65, avatar_url:"pokemonImages/gourgeist.png")
Pokemon.create(name: "Goodra", trainer_id: 30, type1_id:"DRAGON", type2_id: nil, level: 66, avatar_url:"pokemonImages/goodra.png")
Pokemon.create(name: "Gardevoir", trainer_id: 30, type1_id:"PSYCHIC", type2_id:"FAIRY", level: 68, avatar_url:"pokemonImages/gardevoir.png")

Pokemon.create(name: "Hariyama", trainer_id: 31, type1_id:"FIGHTING", type2_id: nil, level: 54, avatar_url:"pokemonImages/hariyama.png")
Pokemon.create(name: "Primeape", trainer_id: 31, type1_id:"FIGHTING", type2_id: nil, level: 54, avatar_url:"pokemonImages/primeape.png")
Pokemon.create(name: "Bewear", trainer_id: 31, type1_id:"FIGHTING", type2_id:"NORMAL", level: 54, avatar_url:"pokemonImages/bewear.png")
Pokemon.create(name: "Poliwrath", trainer_id: 31, type1_id:"WATER", type2_id:"FIGHTING", level: 54, avatar_url:"pokemonImages/poliwrath.png")
Pokemon.create(name: "Crabominable", trainer_id: 31, type1_id:"FIGHTING", type2_id:"ICE", level: 55, avatar_url:"pokemonImages/crabominable.png")

Pokemon.create(name: "Armaldo", trainer_id: 32, type1_id:"ROCK", type2_id:"BUG", level: 56, avatar_url:"pokemonImages/armaldo.png")
Pokemon.create(name: "Cradily", trainer_id: 32, type1_id:"ROCK", type2_id:"GRASS", level: 56, avatar_url:"pokemonImages/cradily.png")
Pokemon.create(name: "Gigalith", trainer_id: 32, type1_id:"ROCK", type2_id: nil, level: 56, avatar_url:"pokemonImages/gigalith.png")
Pokemon.create(name: "Probopass", trainer_id: 32, type1_id:"ROCK", type2_id:"DRAGON", level: 56, avatar_url:"pokemonImages/probopass.png") 
Pokemon.create(name: "Lycanroc", trainer_id: 32, type1_id:"ROCK", type2_id: nil, level: 57, avatar_url:"pokemonImages/lycanroc.png")

Pokemon.create(name: "Banette", trainer_id: 33, type1_id:"GHOST", type2_id: nil, level: 56, avatar_url:"pokemonImages/banette.png")
Pokemon.create(name: "Drifblim", trainer_id: 33, type1_id:"GHOST", type2_id:"FLYING", level: 56, avatar_url:"pokemonImages/drifblim.png")
Pokemon.create(name: "Dhelmise", trainer_id: 33, type1_id:"GHOST", type2_id:"GRASS", level: 56, avatar_url:"pokemonImages/dhelmise.png")
Pokemon.create(name: "Froslass", trainer_id: 33, type1_id:"GHOST", type2_id:"ICE", level: 56, avatar_url:"pokemonImages/froslass.png")
Pokemon.create(name: "Palossand", trainer_id: 33, type1_id:"GHOST", type2_id:"GROUND", level: 57, avatar_url:"pokemonImages/palossand.png")

Pokemon.create(name: "Braviary", trainer_id: 34, type1_id:"NORMAL", type2_id:"FLYING", level: 56, avatar_url:"pokemonImages/braviary.png")
Pokemon.create(name: "Hawlucha", trainer_id: 34, type1_id:"FLYING", type2_id:"FIGHTING", level: 56, avatar_url:"pokemonImages/hawlucha.png")
Pokemon.create(name: "Oricorio", trainer_id: 34, type1_id:"FLYING", type2_id:"FIRE", level: 56, avatar_url:"pokemonImages/oricorio.png")
Pokemon.create(name: "Mandibuzz", trainer_id: 34, type1_id:"FLYING", type2_id:"DARK", level: 56, avatar_url:"pokemonImages/mandibuzz.png")
Pokemon.create(name: "Toucannon", trainer_id: 34, type1_id:"NORMAL", type2_id:"FLYING", level: 57, avatar_url:"pokemonImages/toucannon.png")

Pokemon.create(name: "Lycanroc", trainer_id: 35, type1_id:"ROCK", type2_id: nil, level: 57, avatar_url:"pokemonImages/lycanroc.png")
Pokemon.create(name: "Ninetales", trainer_id: 35, type1_id:"ICE", type2_id:"FAIRY", level: 56, avatar_url:"pokemonImages/ninetales.png")
Pokemon.create(name: "Braviary", trainer_id: 35, type1_id:"FLYING", type2_id:"NORMAL", level: 56, avatar_url:"pokemonImages/braviary.png")
Pokemon.create(name: "Magnezone", trainer_id: 35, type1_id:"ICE", type2_id:"ELECTRIC", level: 56, avatar_url:"pokemonImages/magnezone.png")
Pokemon.create(name: "Snorlax", trainer_id: 35, type1_id:"NORMAL", type2_id: nil, level: 56, avatar_url:"pokemonImages/snorlax.png")
Pokemon.create(name: "Decidueye", trainer_id: 35, type1_id:"GRASS", type2_id:"GHOST", level: 58, avatar_url:"pokemonImages/decidueye.png")


puts "✅ Done seeding!"
